// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWdLhxG_Gg1FnMxTDs_H9uNiWKpQQkj-c',
    appId: '1:623498284939:web:8be0f4d3c4503abf9ce98e',
    messagingSenderId: '623498284939',
    projectId: 'kick74-59eee',
    authDomain: 'kick74-59eee.firebaseapp.com',
    storageBucket: 'kick74-59eee.appspot.com',
    measurementId: 'G-RFY9XCKEGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvypwhVM7VXlcB1DQ-RMfCkKkheaRX9dE',
    appId: '1:623498284939:android:74415dfeafb19c0f9ce98e',
    messagingSenderId: '623498284939',
    projectId: 'kick74-59eee',
    storageBucket: 'kick74-59eee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmdekbnDK5K8zdlhZpchvPsSQWiMQmzus',
    appId: '1:623498284939:ios:82bd208fb5ab8a889ce98e',
    messagingSenderId: '623498284939',
    projectId: 'kick74-59eee',
    storageBucket: 'kick74-59eee.appspot.com',
    iosClientId: '623498284939-840i710llqigm6qejrai5qri8an6coqg.apps.googleusercontent.com',
    iosBundleId: 'com.khaterCS.kick74',
  );
}
